
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.SoftBevelBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.*;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author user
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu(String username, int tableNumber, Table tableFrame, Connection con) throws SQLException {

        try {
            this.con = con;
            st = con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

        initComponents();
        this.tableNumber = tableNumber;
        this.tableFrame = tableFrame;
        count = 1;
        model = (DefaultTableModel) jTable2.getModel();
        this.username = username;
        getCategories();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        categoryPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        categoryListedNamesPanel = new javax.swing.JPanel();
        tableContentPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        payButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        totalPriceTextField = new javax.swing.JTextField();
        goToTableFrameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(this.MAXIMIZED_BOTH);

        mainPanel.setBackground(new java.awt.Color(60, 62, 73));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        categoryPanel.setBackground(new java.awt.Color(55, 58, 73));
        categoryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kategorite");
        categoryPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 398, -1));
        categoryPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 270, -1));

        categoryListedNamesPanel.setBackground(new java.awt.Color(55, 58, 73));
        categoryListedNamesPanel.setName(""); // NOI18N
        categoryListedNamesPanel.setPreferredSize(new java.awt.Dimension(370, 100));
        categoryListedNamesPanel.setLayout(new java.awt.GridLayout(20, 1));
        categoryPanel.add(categoryListedNamesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 370, 1100));

        mainPanel.add(categoryPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1363));

        tableContentPanel.setBackground(new java.awt.Color(60, 62, 73));
        tableContentPanel.setForeground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr", "Product", "Quantity", "Price", "Total price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(2);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(70);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(20);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(25);
            jTable2.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        payButton.setText("Paguaj");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        printButton.setText("Printo");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        totalLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalLabel.setText("Total:");
        totalLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        totalPriceTextField.setBackground(new java.awt.Color(60, 62, 73));
        totalPriceTextField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        totalPriceTextField.setForeground(new java.awt.Color(255, 255, 255));
        totalPriceTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalPriceTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout tableContentPanelLayout = new javax.swing.GroupLayout(tableContentPanel);
        tableContentPanel.setLayout(tableContentPanelLayout);
        tableContentPanelLayout.setHorizontalGroup(
            tableContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableContentPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(tableContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tableContentPanelLayout.createSequentialGroup()
                        .addGroup(tableContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(payButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tableContentPanelLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tableContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(printButton, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(totalPriceTextField))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        tableContentPanelLayout.setVerticalGroup(
            tableContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableContentPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tableContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalPriceTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tableContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        mainPanel.add(tableContentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 200, 510, 520));

        goToTableFrameButton.setText("Tavolina");
        goToTableFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToTableFrameButtonActionPerformed(evt);
            }
        });
        mainPanel.add(goToTableFrameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payButtonActionPerformed

    private void goToTableFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToTableFrameButtonActionPerformed
        ((Window) tableFrame).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_goToTableFrameButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        if (model.getRowCount() > 0) {
            try {
                ps = con.prepareStatement("insert into Invoice(User_ID,Date, Price, TableNumber) select Id , strftime('%d-%m-%Y %H:%M:%S', datetime('now')), ?, ? from User where Username=?");
                ps.setString(3, username);
                ps.setInt(2, tableNumber);
                ps.setDouble(1, Double.parseDouble(totalPriceTextField.getText()));
                ps.execute();
                ps.close();
                rs = st.executeQuery("select last_insert_rowid()");
                int invoice_ID = rs.getInt(1);
                for (int i = 0; i < model.getRowCount(); i++) {
                    ps = con.prepareStatement("insert into M_Invoice_Item (Invoice_ID, Item_ID, Quantity) select ?, ID, ? from Item where Name=?");
                    ps.setInt(1, invoice_ID);
                    ps.setInt(2, (int) model.getValueAt(i, 2));
                    ps.setString(3, (String) model.getValueAt(i, 1));
                    ps.execute();
                    ps.close();
                }
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "The invoice is empty");
        }
    }//GEN-LAST:event_printButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Menu("username", 1, new Table("username", new LogIn(), DriverManager.getConnection("jdbc:sqlite:C:/SQLite/BarTech.db")), DriverManager.getConnection("jdbc:sqlite:C:/SQLite/BarTech.db")).setVisible(true);
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException | SQLException ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel categoryListedNamesPanel;
    private javax.swing.JPanel categoryPanel;
    private javax.swing.JButton goToTableFrameButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton payButton;
    private javax.swing.JButton printButton;
    private javax.swing.JPanel tableContentPanel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField totalPriceTextField;
    // End of variables declaration//GEN-END:variables
    private String username;
    private int count; //to cout the number of products in the invoice
    private int tableNumber;
    private DefaultTableModel model;
    private Table tableFrame;
    private static Connection con;
    private PreparedStatement ps;
    private Statement st, st1;
    private ResultSet rs, rs1;
    private JPanel[] categoryNamePanel, indNamePanel, productDisplayPanel;

    private void setColor(JPanel panel, JPanel indicator) {
        panel.setBackground(new Color(78, 81, 98));
        indicator.setOpaque(true);
    }

    private void resetColor(JPanel[] panel, JPanel currentNamePanel, JPanel[] indicator, JPanel currentIndicatorPanel) {
        for (int i = 0; i < panel.length; i++) {
            if (panel[i] != currentNamePanel) {
                panel[i].setBackground(new Color(55, 58, 73));
            }
        }
        for (int i = 0; i < indicator.length; i++) {
            if (indicator[i] != currentIndicatorPanel) {
                indicator[i].setOpaque(false);
            }
        }
    }

    private void ItemInfo(String name, DefaultTableModel model, int Price) {        //adds items in the table on button click
        Object[] itemInfo = new Object[5];
        int rows = jTable2.getRowCount();

        int i = 0;
        boolean flag = true;
        while (i < rows && flag == true) {
            if ((jTable2.getValueAt(i, 1)).equals(name)) {
                int quantity = Integer.parseInt(model.getValueAt(i, 2).toString());
                quantity++;
                model.setValueAt(quantity, i, 2);
                model.setValueAt(quantity * Price, i, 4);
                flag = false;
            }
            i++;
        }
        if (flag == true) {
            itemInfo[0] = count;
            itemInfo[1] = name;
            itemInfo[2] = 1;
            itemInfo[3] = Price;
            itemInfo[4] = (Integer.parseInt(itemInfo[2].toString()) * Price);
            model.addRow(itemInfo);
            count++;
        }
    }

    private void setPanel(JPanel panel) {  //makes visible the coresponding panel of clicked category
        panel.setVisible(true);
    }

    private void resetPanel(JPanel[] panel, JPanel currentPanel) {  //makes invisible all other panels
        for (int i = 0; i < panel.length; i++) {
            if (panel[i] != currentPanel) {
                panel[i].setVisible(false);
            }
        }
    }

    private void getTotalPrice() {            //shows the total price of the table
        double priceSum = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            double price = (double) ((Integer) model.getValueAt(i, 4));
            priceSum += price;

        }
        totalPriceTextField.setText(Double.toString(priceSum));
    }

    private void getCategories() throws SQLException {
        st = con.createStatement();
        st1 = con.createStatement();
        rs = st.executeQuery("Select count(*) from Category");
        int categoryRowsNumber = rs.getInt(1);
        rs.close();
        rs = st.executeQuery("Select Code from Category");
        int rowCount = 0;
        categoryNamePanel = new JPanel[categoryRowsNumber];
        productDisplayPanel = new JPanel[categoryRowsNumber];
        indNamePanel = new JPanel[categoryRowsNumber];
        while (rs.next()) {
            categoryNamePanel[rowCount] = new JPanel();
            categoryNamePanel[rowCount].setSize(322, 71);
            categoryNamePanel[rowCount].setBackground(new Color(55, 58, 73));
            categoryNamePanel[rowCount].setBorder(new SoftBevelBorder(SoftBevelBorder.RAISED));
            indNamePanel[rowCount] = new JPanel();
            indNamePanel[rowCount].setBackground(Color.white);
            indNamePanel[rowCount].setOpaque(false);
            categoryNamePanel[rowCount].setLayout(new GroupLayout(categoryNamePanel[rowCount]));
            String categoryName = rs.getString("Code");
            JLabel label = new JLabel(categoryName);
            label.setFont(new Font("Dialog", Font.PLAIN, 36));
            label.setForeground(Color.white);
            label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            setCategoryPanelLayout(rowCount, label, categoryRowsNumber);
            associatedProductsPanel(rowCount, categoryName);
            categoryListedNamesPanel.add(categoryNamePanel[rowCount]);
            int currentRow = rowCount;                // should assing the rowCount to another variable because it gives an error in the mouseListener Class
            categoryNamePanel[rowCount].addMouseListener(new java.awt.event.MouseAdapter() {
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    setColor(categoryNamePanel[currentRow], indNamePanel[currentRow]);
                    resetColor(categoryNamePanel, categoryNamePanel[currentRow], indNamePanel, indNamePanel[currentRow]);
                    setPanel(productDisplayPanel[currentRow]);
                    resetPanel(productDisplayPanel, productDisplayPanel[currentRow]);
                }
            });
            rowCount++;
        }
        rs.close();
        setColor(categoryNamePanel[0], indNamePanel[0]); //The first category is shown as default
        setPanel(productDisplayPanel[0]);
    }

    private void setCategoryPanelLayout(int rowCount, JLabel label, int userCount) // this method is used in getUsers method.
    {
        GroupLayout[] ind = new GroupLayout[userCount];
        GroupLayout[] name = new GroupLayout[userCount];

        ind[rowCount] = new javax.swing.GroupLayout(indNamePanel[rowCount]);
        indNamePanel[rowCount].setLayout(ind[rowCount]);
        ind[rowCount].setHorizontalGroup(
                ind[rowCount].createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 3, Short.MAX_VALUE)
        );
        ind[rowCount].setVerticalGroup(
                ind[rowCount].createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        name[rowCount] = new javax.swing.GroupLayout(categoryNamePanel[rowCount]);
        categoryNamePanel[rowCount].setLayout(name[rowCount]);
        name[rowCount].setHorizontalGroup(
                name[rowCount].createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, name[rowCount].createSequentialGroup()
                                .addComponent(indNamePanel[rowCount], javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
        );
        name[rowCount].setVerticalGroup(
                name[rowCount].createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(indNamePanel[rowCount], javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
    }

    private void associatedProductsPanel(int rowCount, String CategoryName) throws SQLException {
        productDisplayPanel[rowCount] = new JPanel();
        productDisplayPanel[rowCount].setPreferredSize(new Dimension(752, 513));
        productDisplayPanel[rowCount].setBackground(new Color(60, 62, 73));
        productDisplayPanel[rowCount].setVisible(false);
        productDisplayPanel[rowCount].setLayout(new FlowLayout(FlowLayout.LEFT));
        rs1 = st1.executeQuery("Select count(*) as NR from Category c inner join Item i on c.ID= i.Category_ID where c.Code='" + CategoryName + "'");
        int numberOfAssociatedItems = rs1.getInt("NR");
        int indexOfItem = 0;
        rs1.close();
        JButton[] productButtons = new JButton[numberOfAssociatedItems];
        rs1 = st1.executeQuery("Select i.Name, i.Price from Category c inner join Item i on c.ID= i.Category_ID where c.Code='" + CategoryName + "'");
        while (rs1.next()) {
            String productName = rs1.getString("Name");
            int productPrice = rs1.getInt("Price");

            productButtons[indexOfItem] = new JButton(rs1.getString("Name"));
            productButtons[indexOfItem].setPreferredSize(new Dimension(96, 55));
            productButtons[indexOfItem].addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent event) {

                    ItemInfo(productName, model, productPrice);

                }
            });

            productDisplayPanel[rowCount].add(productButtons[indexOfItem]);
            indexOfItem++;
        }

        mainPanel.add(productDisplayPanel[rowCount], new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));
        rs1.close();
    }
}
